# macro for batch run of 10M events in NaI simulation with Co-60 source located at side of detector 1 cm from bottom
# initialize multithreading
/run/numberOfThreads 8
/run/initialize
# specify isotope
/gun/particle ion
/gun/ion 27 60 0 0
# set momentum to 0, directed in toward detector
/gun/direction -1 0 0
/gun/momentumAmp 0
# position is 1mm from -x side of cylinder, 1cm from bottom to simulate a source puck
/gun/position 6.7675 0 1 cm

/run/beamOn 1000000
